### ISSUE TITLE
Hello rss competitor!

### ISSUE THREAD

**Issue by ArjixWasTaken** [CoolnsX/anime-rss#1]

**Comment by CoolnsX** [comment]
Yo

**Comment by CoolnsX** [comment]
Also i m not competitor here, open source is not about competition, it about choice.. also i m doing only one source..

**Comment by ArjixWasTaken** [comment]
> open source is not about competition, it about choice

The choice is for the users, the competition is for the developers, and I was just making a joke lol

**Comment by CoolnsX** [comment]
yeah i know lol, sorry if my tone seems bad..

**Comment by CoolnsX** [comment]
Also this is not for users, It's for my discord server
